name: Android Only
on:
  workflow_dispatch

jobs:
  build-android:
    name: Android
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      name: Android
      os: macos-15
      setupCommand: sh ./setup/unix.sh
      buildArgs: "android -ONLY_ARM64"
      artifactName: androidBuild
      artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"